import sqlite3
from pathlib import Path


# Store the database inside the backend folder
DATABASE_PATH = Path(__file__).resolve().parent / "gimes.db"


def get_connection():
    """Create and return a connection to the GIMES SQLite database."""
    connection = sqlite3.connect(DATABASE_PATH)
    return connection


def init_db():
    """Create all required GIMES database tables if they do not already exist."""
    connection = get_connection()
    cursor = connection.cursor()

    # Crowd data received from the computer vision system
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS crowd_data (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            zone_density_json TEXT NOT NULL,
            vibration_flag INTEGER NOT NULL DEFAULT 0
        )
    """)

    # Individual sensor readings
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS sensor_data (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            sensor_type TEXT NOT NULL,
            value REAL NOT NULL
        )
    """)

    # Evacuation alerts generated by the system
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS alerts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            action_taken INTEGER,
            alert_text TEXT,
            language TEXT
        )
    """)

    # QR-based occupant check-in/check-out information
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS qr_occupancy (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id TEXT NOT NULL,
            checkin_time TEXT,
            checkout_time TEXT,
            status TEXT NOT NULL
        )
    """)

    connection.commit()
    connection.close()